const BCMF_GREEN       = "#16a34a";
const BCMF_GREEN_DARK  = "#14532d";
const BCMF_GREEN_LIGHT = "#dcfce7";

export function getStyles(isMobile = false) {
  return {
    page: {
      minHeight: "100vh",
      background: "#f4f6fb",
      padding: isMobile ? 12 : 30,
      fontFamily: "Arial, sans-serif",
      boxSizing: "border-box",
    },
    header: {
      background: `linear-gradient(135deg, #0f172a 0%, ${BCMF_GREEN_DARK} 60%, ${BCMF_GREEN} 100%)`,
      color: "white",
      borderRadius: isMobile ? 16 : 25,
      padding: isMobile ? 16 : 25,
      display: "flex",
      alignItems: isMobile ? "flex-start" : "center",
      justifyContent: "space-between",
      flexDirection: isMobile ? "column" : "row",
      flexWrap: "wrap",
      gap: isMobile ? 14 : 20,
    },
    brand: {
      display: "flex",
      alignItems: "center",
      gap: isMobile ? 12 : 18,
      width: isMobile ? "100%" : "auto",
    },
    logo: {
      height: isMobile ? 58 : 80,
      width: isMobile ? 58 : 80,
      objectFit: "contain",
      background: "white",
      borderRadius: isMobile ? 12 : 18,
      padding: 8,
      flexShrink: 0,
    },
    title: {
      margin: 0,
      fontSize: isMobile ? 24 : 36,
      lineHeight: 1.1,
    },
    subtitle: {
      margin: "5px 0 0",
      fontSize: isMobile ? 13 : 16,
    },
    select: {
      padding: 12,
      borderRadius: 12,
      border: "none",
      fontWeight: "bold",
      width: isMobile ? "100%" : "auto",
    },
    userPill: {
      background: "rgba(255,255,255,.18)",
      padding: "10px 15px",
      borderRadius: 999,
      fontWeight: "bold",
      width: isMobile ? "100%" : "auto",
      textAlign: "center",
      boxSizing: "border-box",
    },
    kpis: {
      display: "grid",
      gridTemplateColumns: isMobile ? "1fr 1fr" : "repeat(auto-fit, minmax(190px, 1fr))",
      gap: isMobile ? 10 : 18,
      marginTop: isMobile ? 16 : 25,
    },
    kpi: {
      background: "white",
      padding: isMobile ? 14 : 20,
      borderRadius: isMobile ? 14 : 18,
      boxShadow: "0 4px 12px rgba(0,0,0,.08)",
      borderTop: `5px solid ${BCMF_GREEN}`,
    },
    grid: {
      display: "grid",
      gridTemplateColumns: isMobile ? "1fr" : "repeat(auto-fit, minmax(310px, 1fr))",
      gap: isMobile ? 12 : 20,
      marginTop: isMobile ? 12 : 20,
    },
    card: {
      background: "white",
      padding: isMobile ? 16 : 22,
      borderRadius: isMobile ? 16 : 20,
      boxShadow: "0 4px 12px rgba(0,0,0,.08)",
      cursor: "pointer",
      boxSizing: "border-box",
    },
    hero: {
      background: "white",
      padding: isMobile ? 18 : 30,
      borderRadius: isMobile ? 16 : 25,
      boxShadow: "0 4px 12px rgba(0,0,0,.08)",
      marginTop: isMobile ? 16 : 25,
      borderTop: `6px solid ${BCMF_GREEN}`,
    },
    badge: {
      display: "inline-block",
      background: BCMF_GREEN,
      color: "white",
      padding: "6px 12px",
      borderRadius: 999,
      fontSize: 13,
      fontWeight: "bold",
    },
    progressBack: {
      width: "100%",
      height: 12,
      background: "#eee",
      borderRadius: 20,
      overflow: "hidden",
      margin: "12px 0",
    },
    progressFront: {
      height: "100%",
      borderRadius: 20,
    },
    link: {
      marginTop: 15,
      color: BCMF_GREEN,
      fontWeight: "bold",
      display: "inline-block",
    },
    backButton: {
      marginTop: 25,
      background: "#222",
      color: "white",
      border: "none",
      padding: "12px 18px",
      borderRadius: 12,
      cursor: "pointer",
      fontWeight: "bold",
      width: isMobile ? "100%" : "auto",
    },
    orangeButton: {
      background: BCMF_GREEN,
      color: "white",
      border: "none",
      padding: isMobile ? "14px 18px" : "12px 18px",
      borderRadius: 12,
      cursor: "pointer",
      fontWeight: "bold",
      fontSize: isMobile ? 15 : 14,
      width: isMobile ? "100%" : "auto",
    },
    darkButton: {
      background: "#222",
      color: "white",
      border: "none",
      padding: isMobile ? "14px 18px" : "12px 18px",
      borderRadius: 12,
      cursor: "pointer",
      fontWeight: "bold",
      fontSize: isMobile ? 15 : 14,
      width: isMobile ? "100%" : "auto",
    },
    disabledButton: {
      background: "#aaa",
      color: "white",
      border: "none",
      padding: "12px 18px",
      borderRadius: 12,
      cursor: "not-allowed",
      fontWeight: "bold",
      width: isMobile ? "100%" : "auto",
    },
    redButton: {
      background: "#c0392b",
      color: "white",
      border: "none",
      padding: isMobile ? "14px 18px" : "12px 18px",
      borderRadius: 12,
      cursor: "pointer",
      fontWeight: "bold",
      width: isMobile ? "100%" : "auto",
    },
    adminNotice: {
      background: BCMF_GREEN_LIGHT,
      border: `1px solid ${BCMF_GREEN}`,
      color: BCMF_GREEN_DARK,
      padding: 15,
      borderRadius: 15,
      marginTop: 20,
      fontWeight: "bold",
    },
    teamBadge: {
      display: "inline-block",
      background: "#7c3aed",
      color: "white",
      padding: "4px 10px",
      borderRadius: 999,
      fontSize: 12,
      fontWeight: "bold",
    },
    badgesContainer: {
      display: "flex",
      flexWrap: "wrap",
      gap: 6,
      marginTop: 8,
    },
    tableWrapper: {
      width: "100%",
      overflowX: "auto",
    },
    modal: {
      width: isMobile ? "calc(100vw - 24px)" : 520,
      maxWidth: "100%",
      maxHeight: isMobile ? "90vh" : "auto",
      overflowY: "auto",
      boxSizing: "border-box",
    },
    panel: {
      background: "white",
      padding: isMobile ? 16 : 24,
      borderRadius: isMobile ? 16 : 22,
      boxShadow: "0 4px 12px rgba(0,0,0,.08)",
      marginTop: isMobile ? 16 : 25,
      display: "flex",
      flexDirection: "column",
      gap: 12,
      boxSizing: "border-box",
    },
    // fontSize 16px sur mobile = évite le zoom automatique iOS sur les inputs
    input: {
      width: "100%",
      padding: isMobile ? "14px 14px" : "12px 14px",
      borderRadius: 12,
      border: "1px solid #d1d5db",
      fontSize: isMobile ? 16 : 15,
      boxSizing: "border-box",
    },
    checkboxGrid: {
      display: "grid",
      gridTemplateColumns: isMobile ? "1fr 1fr" : "repeat(auto-fit, minmax(160px, 1fr))",
      gap: 10,
      marginTop: 6,
      marginBottom: 8,
    },
    checkboxLabel: {
      display: "flex",
      alignItems: "center",
      gap: 8,
      background: "#f8fafc",
      padding: "10px 12px",
      borderRadius: 12,
      border: "1px solid #e5e7eb",
      fontSize: 14,
      cursor: "pointer",
    },
    eventTitle: {
      marginTop: 12,
      marginBottom: 10,
      fontSize: isMobile ? 18 : 24,
      lineHeight: 1.2,
    },
    eventInfo: {
      margin: "6px 0",
      fontSize: isMobile ? 14 : 15,
    },
    eventFooter: {
      marginTop: 12,
      color: BCMF_GREEN,
      fontWeight: "bold",
    },
    eventHeroTitle: {
      margin: "14px 0 10px",
      fontSize: isMobile ? 22 : 36,
      lineHeight: 1.15,
    },
    eventHeroInfo: {
      margin: "8px 0",
      fontSize: isMobile ? 14 : 17,
    },
    sectionTitle: {
      marginTop: isMobile ? 24 : 30,
      fontSize: isMobile ? 20 : 26,
    },
    missionTitle: {
      marginTop: 0,
      marginBottom: 10,
      fontSize: isMobile ? 18 : 22,
    },
    missionInfo: {
      margin: "7px 0",
      fontSize: isMobile ? 14 : 15,
    },
    assignedList: {
      background: "#f8fafc",
      padding: 10,
      borderRadius: 12,
      marginTop: 10,
      marginBottom: 12,
      fontSize: 14,
    },
    buttonRow: {
      display: "flex",
      flexDirection: isMobile ? "column" : "row",
      gap: 10,
      marginTop: 12,
      flexWrap: "wrap",
    },
    editBox: {
      marginTop: 15,
      display: "flex",
      flexDirection: "column",
      gap: 10,
    },
  };
}

// Rétrocompatibilité — les fichiers non encore migrés continuent de fonctionner
export const styles = getStyles(
  typeof window !== "undefined" ? window.innerWidth <= 768 : false
);
